version: "3.9"

services:
  api:
    container_name: desafio-api
    image: node:12.20.1-buster-slim
    working_dir: /opt/app
    command: ["yarn", "dev"]
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./:/opt/app
    networks:
      - host
    depends_on:
      - db
  db:
    container_name: desafio-db
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    networks:
      - host
    environment:
      - POSTGRES_PASSWORD=docker
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

networks:
  host:
    driver: bridge
    name: desafio-network

volumes:
  postgres-data:
